# Generated by Django 4.2 on 2023-04-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssspi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='apellido',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nombre',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Nombre'),
        ),
    ]
