# Generated by Django 4.2 on 2023-04-19 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssspi', '0002_profile_apellido_profile_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsim',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ssspi.profile', verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='formsim',
            name='unidad_flujo_masico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ssspi.unidad_flujo_masico'),
        ),
        migrations.AlterField(
            model_name='formsim',
            name='unidad_potencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ssspi.unidad_potencia'),
        ),
        migrations.AlterField(
            model_name='formsim',
            name='unidad_presion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ssspi.unidad_presion'),
        ),
    ]
