# Generated by Django 4.2 on 2023-04-21 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssspi', '0003_formsim_profile_alter_formsim_unidad_flujo_masico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formsim',
            name='procesos',
        ),
        migrations.AlterField(
            model_name='formsim',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssspi.profile', verbose_name='Usuario'),
        ),
        migrations.DeleteModel(
            name='Procesos',
        ),
    ]
