# Generated by Django 4.2 on 2023-05-05 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssspi', '0005_ubicacion_latitud_personalizada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formsim',
            name='profile',
        ),
        migrations.AddField(
            model_name='formsim',
            name='simulacion',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Simulacion', to='ssspi.simulaciones'),
            preserve_default=False,
        ),
    ]
