# Generated by Django 4.2 on 2023-05-09 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssspi', '0007_formsim_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formsim',
            name='aplicacion',
        ),
        migrations.AlterField(
            model_name='formsim',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ssspi.profile', verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='formsim',
            name='simulacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Simulacion', to='ssspi.simulaciones'),
        ),
    ]
