# Generated by Django 4.2 on 2023-05-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssspi', '0009_archivotmy_simulaciones_archivo_tmy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorSimulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_simulacion', models.IntegerField(default=0)),
            ],
        ),
    ]
